Repository Passtival/passtival-client, pull requests merged in 2025-09, with the labels that each got.

#115 Feature: 부스 체험 활동 페이지 구현
  src/pages/booth-detail/booth-detail.tsx
  src/pages/booth-detail/components/activity-info.tsx
Labels: 📣 feature, ☃️ 연희

#129 Feat: 부스 메인 페이지 구현
  src/pages/booth/booth.css.ts
  src/pages/booth/booth.tsx
  src/pages/booth/constants/.gitkeep
  src/pages/booth/constants/booth-text.ts
  src/shared/components/card/card.css.ts
  src/shared/components/card/card.tsx
  src/shared/components/chip/chip.css.ts
  src/shared/components/timeTable/timeTable.css.ts
  src/shared/components/timeTable/timeTable.tsx
Labels: 📣 feature, 🎤 승택

#138 Feat: 분실물 조회 api 연동
  package.json
  src/pages/lost-items/apis/.gitkeep
  src/pages/lost-items/apis/queries.ts
  src/pages/lost-items/lost-items.tsx
  src/pages/lost-items/types/.gitkeep
  src/pages/lost-items/types/types.ts
  src/shared/apis/config/end-point.ts
  src/shared/apis/config/interceptor.ts
  src/shared/apis/domain/blind-match/queries.ts
  src/shared/apis/domain/booth/queries.ts
  src/shared/apis/domain/home/queries.ts
  src/shared/apis/domain/land/queries.ts
  src/shared/apis/domain/lost-items/queries.ts
  src/shared/apis/domain/ticket/queries.ts
  src/shared/apis/keys/query-key.ts
  src/shared/apis/types/schema.d.ts
  src/shared/components/Thumbnail/Thumbnail.tsx
  src/shared/components/card/card.tsx
Labels: 📣 feature, 🦁 정훈

#147 Fix: 디자인 시스템 변경
  src/app/App.tsx
  src/pages/blind-match/components/agreement/agreement.tsx
  src/pages/blind-match/components/apply-after/complete.css.ts
  src/pages/blind-match/components/entry/entry.css.ts
  src/pages/blind-match/components/message/message.css.ts
  src/pages/blind-match/components/result/result.css.ts
  src/pages/blind-match/components/use-info-form/use-info-form.tsx
  src/pages/blind-match/components/user-info/user-info.css.ts
  src/pages/blind-match/utils/formattied-number.ts
  src/pages/booth-detail/components/booth-detail-item/booth-detail-item.css.ts
  src/pages/booth-detail/components/booth-detail-item/booth-detail-item.tsx
  src/pages/booth/booth.tsx
  src/pages/info-share/info-share.css.ts
  src/pages/info-share/info-share.tsx
  src/pages/lost-item-report/lost-item-report.css.ts
  src/pages/lost-item-report/lost-item-report.tsx
  src/pages/lost-items/lost-items.css.ts
  src/router/global-layout.tsx
  src/router/routes/global-routes.tsx
  src/shared/components/add-image/add-image.css.ts
  src/shared/components/add-image/add-image.tsx
  src/shared/components/agreement-option/agreement-option.css.ts
  src/shared/components/agreement-option/agreement-option.tsx
  src/shared/components/bottom-navigation/bottom-navigation.css.ts
  src/shared/components/button/button.css.ts
  src/shared/components/card/card.css.ts
  src/shared/components/card/card.tsx
  src/shared/components/chip/chip.css.ts
  src/shared/components/detail-desctipion/detail-description.css.ts
  src/shared/components/detail-eventinfo/detail-info.css.ts
  src/shared/components/detail-header/detail-header.css.ts
  src/shared/components/drop-down/drop-down.css.ts
  src/shared/components/drop-down/drop-down.tsx
  src/shared/components/input/input.css.ts
  src/shared/components/modal/modal.css.ts
  src/shared/components/tab/tab.css.ts
  src/shared/components/timeTable/timeTable.css.ts
  src/shared/components/timeTable/timeTable.tsx
  src/shared/components/title/title.css.ts
  src/shared/components/title/title.tsx
  src/shared/components/top-navigation/top-navigation.css.ts
  src/shared/styles/global.css.ts
  src/shared/styles/token/color.css.ts
  src/shared/styles/token/font-style.ts
  src/shared/styles/token/typography.css.ts
Labels: 🪛 fix, 🦁 정훈

#145 Feat: 공연 상세 페이지 api 연동
  src/pages/show-detail/apis/queries.ts
  src/pages/show-detail/show-detail.tsx
  src/pages/show-detail/types/types.ts
  src/pages/show-detail/utils/get-time.ts
  src/router/path.ts
  src/shared/apis/config/end-point.ts
  src/shared/apis/keys/query-key.ts
  src/shared/components/detail-desctipion/detail-description.css.ts
  src/shared/components/detail-desctipion/detail-description.tsx
  src/shared/components/detail-eventinfo/detail-info.tsx
  src/shared/components/detail-header/detail-header.tsx
Labels: 📣 feature, 🦦 윤하

#154 Feat: 관리자 페이지 구현 및 로직 구현
  src/pages/admin/admin-login/admin-login.css.ts
  src/pages/admin/admin-login/admin-login.tsx
  src/pages/admin/admin-main/admin-main.css.ts
  src/pages/admin/admin-main/admin-main.tsx
  src/pages/admin/constants/NAVIGATE.ts
  src/pages/admin/constants/TITLE.ts
  src/pages/admin/generate-auth-key/generate-auth-key.css.ts
  src/pages/admin/generate-auth-key/generate-auth-key.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/router.tsx
  src/router/routes/global-routes.tsx
  src/shared/components/button/button.css.ts
  src/shared/components/button/button.tsx
  src/shared/styles/token/color.css.ts
Labels: 📣 feature, 🦁 정훈

#155 Feat: 응모권 온보딩 페이지 구현
  public/ticket.svg
  src/pages/admin/admin-login/admin-login.css.ts
  src/pages/admin/admin-login/admin-login.tsx
  src/pages/admin/admin-main/admin-main.tsx
  src/pages/admin/constants/TITLE.ts
  src/pages/admin/generate-auth-key/generate-auth-key.css.ts
  src/pages/admin/generate-auth-key/generate-auth-key.tsx
  src/pages/ticket-onboarding/constatns/onboarding-text.css.ts
  src/pages/ticket-onboarding/constatns/onboarding-text.tsx
  src/pages/ticket-onboarding/onboarding.css.ts
  src/pages/ticket-onboarding/onboarding.tsx
  src/router/global-layout.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/router.tsx
  src/router/routes/global-routes.tsx
  src/shared/auth/services/token-service.ts
  src/shared/components/bottom-navigation/bottom-navigation.css.ts
Labels: 📣 feature, 🦦 윤하

#152 Feat: land page 첫 화면
  src/pages/land/land.css.ts
  src/pages/land/land.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/routes/global-routes.tsx
Labels: 📣 feature, 🎤 승택

#160 Feat: 랜딩 페이지 수정 및 로직 추가
  package.json
  pnpm-lock.yaml
  src/assets/lottie/lodding.json
  src/assets/svg/logo.svg
  src/pages/land/land.css.ts
  src/pages/land/land.tsx
  src/router/global-layout.tsx
  src/shared/icons/ic_logo.tsx
  src/shared/icons/index.ts
  src/shared/styles/token/font-style.ts
  src/shared/styles/token/typography.css.ts
Labels: 📣 feature, 🦁 정훈

#165 Fix: 번호팅 필수 조건 수정
  src/pages/blind-match/components/entry/entry.tsx
  src/pages/blind-match/components/modal/confirm-modal.tsx
  src/pages/blind-match/components/use-info-form/use-info-form.tsx
Labels: 📣 feature, 🦦 윤하

#169 Feat 관리자 응모권 추천 구현
  src/pages/admin/admin-main/admin-main.tsx
  src/pages/admin/ticket-drawing/components/drawing-button/drawing-button.css.ts
  src/pages/admin/ticket-drawing/components/drawing-button/drawing-button.tsx
  src/pages/admin/ticket-drawing/components/drawing-input/drawing-input.css.ts
  src/pages/admin/ticket-drawing/components/drawing-input/drawing-input.tsx
  src/pages/admin/ticket-drawing/components/drawing-main/drawing-main.css.ts
  src/pages/admin/ticket-drawing/components/drawing-main/drawing-main.tsx
  src/pages/admin/ticket-drawing/components/drawing/drawing.css.ts
  src/pages/admin/ticket-drawing/components/drawing/drawing.tsx
  src/pages/admin/ticket-drawing/components/info-section/info-section.css.ts
  src/pages/admin/ticket-drawing/components/info-section/info-section.tsx
  src/pages/admin/ticket-drawing/components/modal.tsx
  src/pages/admin/ticket-drawing/ticket-drawing.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/routes/global-routes.tsx
Labels: 📣 feature, 🦦 윤하

#167 feat: 에러 및 로딩 페이지 구현
  src/assets/svg/error.svg
  src/pages/error/error.css.ts
  src/pages/error/error.tsx
  src/pages/loading/loading.css.ts
  src/pages/loading/loading.tsx
  src/router/global-error-boundary.tsx
  src/router/router.tsx
  src/shared/icons/ic_error.tsx
  src/shared/icons/index.ts
Labels: 📣 feature, 🦁 정훈

#190 Fix: 전체적인 css 수정사항
  src/pages/blind-match/blind-match.tsx
  src/pages/blind-match/components/apply-after/complete.css.ts
  src/pages/blind-match/components/apply-after/complete.tsx
  src/pages/blind-match/components/entry/entry.css.ts
  src/pages/blind-match/components/message/message.css.ts
  src/pages/blind-match/components/modal/confirm-modal.tsx
  src/pages/blind-match/components/use-info-form/use-info-form.css.ts
  src/pages/blind-match/components/use-info-form/use-info-form.tsx
  src/pages/booth/booth.css.ts
  src/pages/booth/booth.tsx
  src/pages/booth/constants/booth-text.ts
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
  src/pages/land/land.tsx
  src/pages/login/login.tsx
  src/pages/lost-item-info/lost-item-info.css.ts
  src/pages/lost-item-info/lost-item-info.tsx
  src/pages/lost-item-report/lost-item-report.css.ts
  src/pages/lost-items/lost-items.css.ts
  src/pages/lost-items/lost-items.tsx
  src/pages/onboarding/onboarding.css.ts
  src/pages/show-detail/show-detail.tsx
  src/pages/ticket-onboarding/constatns/onboarding-text.css.ts
  src/pages/ticket-onboarding/constatns/onboarding-text.tsx
  src/pages/ticket-onboarding/onboarding.css.ts
  src/pages/ticket-onboarding/onboarding.tsx
  src/pages/ticket/components/chip/chip.css.ts
  src/pages/ticket/ticket.css.ts
  src/pages/ticket/ticket.tsx
  src/router/global-layout.tsx
  src/router/routes/global-routes.tsx
  src/shared/auth/services/token-service.ts
  src/shared/components/Thumbnail/Thumbnail.css.ts
  src/shared/components/bottom-navigation/bottom-navigation.css.ts
  src/shared/components/bottom-navigation/bottom-navigation.tsx
  src/shared/components/card/card.css.ts
  src/shared/components/chip/chip.css.ts
  src/shared/components/header/header.css.ts
  src/shared/components/input/input.css.ts
  src/shared/components/tab/tab.css.ts
  src/shared/components/timeTable/timeTable.css.ts
  src/shared/components/title-info/title-info.css.ts
  src/shared/components/title-info/title-info.tsx
  src/shared/components/top-navigation/top-navigation.css.ts
  src/shared/styles/token/color.css.ts
Labels: 🪛 fix, 🦦 윤하

#192 Fix: Thumbnail 이미지 없을 경우 추가
  src/assets/svg/image.svg
  src/pages/lost-items/lost-items.css.ts
  src/shared/components/Thumbnail/Thumbnail.css.ts
  src/shared/components/Thumbnail/Thumbnail.tsx
  src/shared/icons/ic_image.tsx
  src/shared/icons/index.ts
Labels: 🪛 fix, 🦦 윤하

#183 Feat: 번호팅 api 연동
  src/pages/blind-match/apis/.gitkeep
  src/pages/blind-match/apis/queries.ts
  src/pages/blind-match/components/entry/entry.tsx
  src/pages/blind-match/components/result/success.tsx
  src/pages/blind-match/components/use-info-form/use-info-form.tsx
  src/pages/blind-match/types/.gitkeep
  src/pages/blind-match/types/types.ts
  src/pages/login-callback/login-callback.tsx
  src/shared/apis/config/end-point.ts
  src/shared/apis/keys/query-key.ts
Labels: 📣 feature, 🎤 승택

#217 QA-1: 번호팅 상단 텍스트 오타 수정
  src/pages/blind-match/blind-match.tsx
  src/pages/blind-match/hooks/use-application.ts
Labels: 🪛 fix, ☃️ 연희

#219 fix: span 내용에 띄어쓰기 추가
  src/pages/ticket-onboarding/constatns/onboarding-text.tsx
Labels: 🪛 fix, ☃️ 연희

#223 Feat: 푸드존 상세정보
  src/pages/booth-detail/booth-detail.tsx
  src/pages/booth-detail/components/activity-info.tsx
  src/pages/booth-detail/components/booth-detail.css.ts
  src/pages/booth/components/booth-list.tsx
Labels: 📣 feature, 🦦 윤하

#225 fix: position 수정 및 padding 값 수정
  src/pages/ticket-onboarding/onboarding.css.ts
Labels: 🪛 fix, ☃️ 연희

#228 HOTFIX: 공연 상세 조회 API 수정
  src/pages/show-detail/apis/queries.ts
  src/shared/apis/config/interceptor.ts
  src/shared/apis/types/schema.d.ts
Labels: 🪛 fix, 🦁 정훈

#236 Fix: 번호팅 인풋창 한글 벤
  src/pages/blind-match/components/use-info-form/use-info-form.tsx
Labels: 🪛 fix, 🎤 승택

#239 Feat: 개인정보 동의 TopNavigation 추가
  src/pages/info-share/info-share.css.ts
  src/pages/info-share/info-share.tsx
Labels: 📣 feature, 🎤 승택

#247 Feat: 번호팅 복귀 폼 유지
  src/pages/blind-match/components/agreement/agreement.tsx
  src/pages/blind-match/components/entry/entry.tsx
  src/pages/info-share/info-share.tsx
  src/shared/components/agreement-option/agreement-option.tsx
  src/shared/components/top-navigation/top-navigation.tsx
Labels: 📣 feature, 🎤 승택

#232 Feat: 공지사항, 행사장 지도 이미지 추가
  public/carousel1.jpg
  public/carousel2.jpg
  public/carousel3.jpg
  public/info.png
  public/map1.png
  public/map2.png
  src/pages/booth/booth.css.ts
  src/pages/booth/booth.tsx
  src/pages/home/home.css.ts
  src/pages/home/home.tsx
Labels: 📣 feature, 🦁 정훈

#242 QA-1: 온보딩 페이지 배경이랑 텍스트 겹치는 문제
  src/pages/onboarding/onboarding.css.ts
Labels: 🪛 fix, 🦁 정훈

#254 QA-1: 온보딩 버튼 폰트 변경
  src/pages/onboarding/onboarding.css.ts
Labels: 🪛 fix, 🦁 정훈

#257 fix: 모달창 사용자 정보 순서 변경
  src/pages/blind-match/components/modal/confirm-modal.tsx
Labels: 🪛 fix, 🦦 윤하

#258 QA-1: 개인정보 동의서 페이지 스타일 및 내용 수정
  src/pages/info-share/constants/INFO_SHARE_CONSENT.ts
  src/pages/info-share/info-share.css.ts
  src/pages/info-share/info-share.tsx
Labels: 🪛 fix, 🦁 정훈

#260 Feat: 인증키 새로고침 버튼 추가
  src/pages/admin/generate-auth-key/generate-auth-key.css.ts
  src/pages/admin/generate-auth-key/generate-auth-key.tsx
Labels: 📣 feature, 🦁 정훈

#262 QA-1 응모권 추첨 페이지 정보 저장
  src/pages/admin/ticket-drawing/components/drawing-main/drawing-main.tsx
  src/pages/admin/ticket-drawing/ticket-drawing.tsx
Labels: 🪛 fix, 🦁 정훈

#266 HOTFIX: 번호팅 페이지 로직 수정 및 API boolean상태 추가
  src/pages/blind-match/components/apply-after/complete.css.ts
  src/pages/blind-match/components/user-info/user-info.tsx
  src/pages/blind-match/constants/blind-match-time.ts
  src/pages/blind-match/hooks/use-application.ts
  src/shared/apis/types/schema.d.ts
Labels: 🪛 fix, 🦁 정훈

#269 Fix: 푸드존 체험 활동 Tap 오류
  src/pages/booth-detail/components/activity-info.tsx
  src/pages/booth-detail/components/booth-detail.css.ts
Labels: 🪛 fix, 🎤 승택

#274 QA-2: 메뉴정보 메뉴가 없습니다 추가
  src/pages/booth-detail/components/menu-info.tsx
Labels: 🪛 fix, 🦦 윤하

#277 QA-2: 응모권 캐러셀 너비 수정 및 API값 수정
  src/pages/ticket/components/carousel/carousel.css.ts
  src/pages/ticket/components/carousel/carousel.tsx
  src/pages/ticket/constants/ticket-time.ts
  src/pages/ticket/hooks/use-date-selection.ts
  src/pages/ticket/ticket.tsx
Labels: 🪛 fix, 🦁 정훈

#288 Fix: 마감 시간 및 결과 발표 시간 수정
  src/pages/blind-match/constants/blind-match-time.ts
Labels: 🪛 fix, 🦁 정훈

#297 QA-3: 홈 페이지 축제 정보 일차 표기
  src/pages/home/home.tsx
  src/shared/constants/festivalSchedule.ts
Labels: 📣 feature, 🦁 정훈

#302 QA-3: 부스 상세 정보에서만 ScrollRestoration 적용 안됨 문제 해결
  src/pages/booth-detail/booth-detail.tsx
Labels: 🪛 fix, 🦁 정훈

#306 Fix: 응모권 하단 nav 유지
  src/router/path.ts
  src/shared/components/bottom-navigation/bottom-navigation.tsx
Labels: 🪛 fix, 🎤 승택

#300 QA-3 공연 상세 정보 설명부 조건부 렌더링
  src/pages/show-detail/show-detail.tsx
Labels: 📣 feature, 🦁 정훈

#295 QA-3 번호팅 신청 상태 관리, 매칭 후 결과 관리
  src/pages/blind-match/constants/blind-match-time.ts
  src/pages/blind-match/hooks/use-application.ts
Labels: 🪛 fix, 🦁 정훈

#308 QA-3: 응모권 사용자 정보 입력 유효성 검사 추가
  src/pages/ticket/components/inpur-section/input-section.tsx
Labels: 🪛 fix, 🦦 윤하

#317 Fix: 당첨자 관리 로직 개선 및 상태 업데이트 방식 변경 및 인증키 새로고침 버튼 삭제
  src/pages/admin/generate-auth-key/generate-auth-key.css.ts
  src/pages/admin/generate-auth-key/generate-auth-key.tsx
  src/pages/admin/ticket-drawing/components/drawing-main/drawing-main.tsx
  src/pages/admin/ticket-drawing/components/drawing/drawing.tsx
  src/pages/admin/ticket-drawing/ticket-drawing.tsx
Labels: 🪛 fix, 🦁 정훈

#319 QA-4: 부스 상세 조회 말줄임 수정
  src/pages/blind-match/constants/blind-match-time.ts
  src/pages/booth-detail/components/booth-detail-item/booth-detail-item.css.ts
Labels: 🪛 fix, 🦁 정훈

#321 README.md 업데이트
  README.md
Labels: 📣 feature, 🦁 정훈

#333 Feat: Vercel 사용자 집계 추가
  package.json
  pnpm-lock.yaml
  src/app/main.tsx
Labels: 📣 feature, 🦁 정훈

#336 Feat: Vercel 성능 지표 추가
  package.json
  pnpm-lock.yaml
  src/app/main.tsx
Labels: 📣 feature, 🦁 정훈

#342 Feat: 행사장 지도 이미지 업데이트
  public/map2.webp
Labels: 📣 feature, 🦁 정훈

#347 HotFix: 부스 조회 수정
  src/pages/booth/components/booth-list.tsx
  src/pages/booth/types/types.ts
Labels: 🪛 fix, 🎤 승택

#346 Fix: 한글입력시 ·가능하도록 수정
  src/pages/ticket/components/inpur-section/input-section.tsx
Labels: 🪛 fix, 🦦 윤하

#374 재배포
  src/pages/home/home.tsx
Labels: 🎤 승택
