Repository Passtival/passtival-client, pull requests merged in 2025-08, with the labels that each got.

#2 Init: 프로젝트 초기 세팅
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/.gitkeep
  src/App.tsx
  src/assets/.gitkeep
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ☃️ 정훈, init

#5 [Fix] React 초기세팅 파일 제거
  src/App.tsx
  src/main.tsx
Labels: 🪛 fix, ☃️ 정훈

#6 Production-release(v.0.0.0)
  src/App.tsx
  src/main.tsx
Labels: ☃️ 정훈, 🚀 deploy

#8 [Init] CI / CD 파이프라인 세팅
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  build.sh
  eslint.config.js
  eslint.config.ts
Labels: ☃️ 정훈, 🤖 CI/CD

#14 Init: Discord 알림봇 설정
  .github/workflows/discord-notify.yml
Labels: ☃️ 연희, 🛠️ init

#15 Init: eslint, prettier, husky 세팅
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc
  commitlint.config.cjs
  eslint.config.ts
  package.json
  pnpm-lock.yaml
Labels: ☃️ 윤하, 🛠️ init

#21 init: 라우터 초기세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
  src/pages/booth/booth.tsx
  src/pages/home/home.tsx
  src/pages/land/land.tsx
  src/pages/login-fallback/apis/.gitkeep
  src/pages/login-fallback/components/.gitkeep
  src/pages/login-fallback/constants/.gitkeep
  src/pages/login-fallback/hooks/.gitkeep
  src/pages/login-fallback/login-fallback.tsx
  src/pages/login-fallback/types/.gitkeep
  src/pages/login-fallback/utils/.gitkeep
  src/pages/login/login.tsx
  src/pages/lost-items/lost-items.tsx
  src/pages/ticket/ticket.tsx
  src/router/global-layout.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/router.tsx
  src/router/routes/global-routes.tsx
  tsconfig.app.json
Labels: ☃️ 승택, 🛠️ init

#24 Init: Tanstack Query / Axios 초기세팅
  .env.example
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/router/routes/global-routes.tsx
  src/shared/apis/config/end-point.ts
  src/shared/apis/config/instance.ts
  src/shared/apis/domain/blind-match/queries.ts
  src/shared/apis/domain/booth/queries.ts
  src/shared/apis/domain/home/queries.ts
  src/shared/apis/domain/land/queries.ts
  src/shared/apis/domain/lost-items/queries.ts
  src/shared/apis/domain/ticket/queries.ts
  src/shared/apis/http.ts
  src/shared/apis/keys/query-key.ts
  src/shared/apis/types/api.ts
  src/shared/constants/response.ts
  src/shared/utils/query-client.ts
Labels: 🦁 정훈, 🛠️ init

#29 init: icon svgr 세팅
  package.json
  pnpm-lock.yaml
  scripts/build-icons.ts
  src/assets/svg/booth.svg
  src/assets/svg/calendar.svg
  src/assets/svg/camera.svg
  src/assets/svg/caution.svg
  src/assets/svg/entry.svg
  src/assets/svg/location.svg
  src/assets/svg/lostfind.svg
  src/assets/svg/main.svg
  src/assets/svg/match.svg
  src/assets/svg/time.svg
  src/assets/svg/trashcan.svg
  src/assets/svg/x.svg
  src/shared/assets/.gitkeep
  src/shared/icons/ic_booth.tsx
  src/shared/icons/ic_calendar.tsx
  src/shared/icons/ic_camera.tsx
  src/shared/icons/ic_caution.tsx
  src/shared/icons/ic_entry.tsx
  src/shared/icons/ic_location.tsx
  src/shared/icons/ic_lostfind.tsx
  src/shared/icons/ic_main.tsx
  src/shared/icons/ic_match.tsx
  src/shared/icons/ic_time.tsx
  src/shared/icons/ic_trashcan.tsx
  src/shared/icons/ic_x.tsx
  src/shared/icons/index.ts
  src/svg.d.ts
  vite.config.ts
Labels: ☃️ 윤하, 🛠️ init

#28 init: color, font 시스템 세팅 및 global css 세팅
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/shared/styles/.gitkeep
  src/shared/styles/global.css.ts
  src/shared/styles/index.ts
  src/shared/styles/reset.css.ts
  src/shared/styles/theme-provider.tsx
  src/shared/styles/theme.css.ts
  src/shared/styles/token/color.css.ts
  src/shared/styles/token/font-style.ts
  src/shared/styles/token/typography.css.ts
  src/shared/styles/token/width.css.ts
  src/shared/styles/token/zIndex.css.ts
  tsconfig.json
  vite.config.ts
Labels: ☃️ 승택, 🛠️ init

#32 feat: Chip 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/shared/components/chip/chip.css.ts
  src/shared/components/chip/chip.tsx
Labels: ☃️ 승택, 🛠️ init

#45 HOTFIX: root @shared/icons 삭제
  @shared/icons/ic_booth.tsx
  @shared/icons/ic_calendar.tsx
  @shared/icons/ic_caution.tsx
  @shared/icons/ic_entry.tsx
  @shared/icons/ic_kakaotalk.tsx
  @shared/icons/ic_location.tsx
  @shared/icons/ic_lostfind.tsx
  @shared/icons/ic_main.tsx
  @shared/icons/ic_match.tsx
  @shared/icons/ic_time.tsx
  @shared/icons/ic_trashcan.tsx
  @shared/icons/ic_x.tsx
  @shared/icons/index.ts
Labels: 🪛 fix, 🦦 윤하

#38 Feat: 모달 컴포넌트 구현
  src/shared/components/modal/hooks/use-scroll-lock.ts
  src/shared/components/modal/modal.css.ts
  src/shared/components/modal/modal.tsx
Labels: 📣 feature, 🦁 정훈

#56 Fix: Icon svg currentColor 조건 추가
  scripts/build-icons.ts
  src/assets/svg/arrow_down.svg
  src/assets/svg/check.svg
  src/assets/svg/kakao-talk.svg
  src/assets/svg/trashcan.svg
  src/shared/icons/ic_arrowdown.tsx
  src/shared/icons/ic_check.tsx
  src/shared/icons/ic_time.tsx
  src/shared/icons/index.ts
Labels: 🪛 fix, 🦦 윤하

#50 Feat: Carousel 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/shared/components/carousel/carousel.css.ts
  src/shared/components/carousel/carousel.tsx
  src/shared/components/carousel/slideindicator/slideIndicator.tsx
  src/shared/components/carousel/slideindicator/slideindicator.css.ts
Labels: 📣 feature, 🦦 윤하

#66 Feat: DetailInfo 컴포넌트 구현
  src/shared/components/detail-eventinfo/detail-info.css.ts
  src/shared/components/detail-eventinfo/detail-info.tsx
Labels: 📣 feature, 🦦 윤하

#60 Feat: AgreementOption 컴포넌트 구현
  src/shared/components/agreement-option/agreement-option.css.ts
  src/shared/components/agreement-option/agreement-option.tsx
Labels: 📣 feature, ☃️ 연희

#77 Feat: 분실물 관리자 로그인 페이지
  src/pages/admin-login/admin-login.css.ts
  src/pages/admin-login/admin-login.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/routes/global-routes.tsx
  src/shared/components/input/input.css.ts
  src/shared/components/input/input.tsx
Labels: 📣 feature, 🦦 윤하

#83 Feat: Axios 인터셉터 기반 토큰 자동 재발급 로직 추가
  src/shared/apis/config/instance.ts
  src/shared/apis/config/interceptor.ts
  src/shared/apis/http.ts
  src/shared/apis/types/api.ts
Labels: 📣 feature, 🦁 정훈

#84 Feat: 메인 상세 정보 페이지 구현
  src/pages/show-detail/show-detail.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/routes/global-routes.tsx
  src/shared/components/detail-eventinfo/detail-info.tsx
Labels: 📣 feature, 🦦 윤하

#90 Refactor: App, main 파일 경로 이동
  index.html
  src/app/App.tsx
  src/app/main.tsx
Labels: ⛏️ refactor, 🦁 정훈

#88 Feat: ErrorBoundary / Suspense 세팅
  package.json
  pnpm-lock.yaml
  src/app/App.tsx
  src/pages/error/error.tsx
  src/router/global-error-boundary.tsx
  src/router/router.tsx
Labels: 📣 feature, 🦁 정훈

#82 Feat: TimeTable컴포넌트 구현
  src/assets/svg/clock.svg
  src/shared/components/timeTable/timeTable.css.ts
  src/shared/components/timeTable/timeTable.tsx
  src/shared/constants/festivalSchedule.ts
  src/shared/icons/ic_clock.tsx
  src/shared/icons/index.ts
  src/shared/utils/getOpeningHours.ts
Labels: ☃️ 승택, 🛠️ init

#102 Feat: 카카오 로그인 버튼 구현
  .env.example
  src/shared/components/kakao-login-button/kakao-login-button.css.ts
  src/shared/components/kakao-login-button/kakao-login-button.tsx
Labels: 📣 feature, 🦁 정훈

#93 Feat: 부스 정보 상세 페이지 구현
  src/pages/booth-detail/booth-detail.tsx
  src/pages/booth-detail/booth-info.tsx
  src/router/lazy.ts
  src/router/path.ts
  src/router/routes/global-routes.tsx
Labels: 📣 feature, 🦦 윤하

#111 fix: Tab 컴포넌트 반응형 고려
  src/shared/components/tab/tab.css.ts
  src/shared/components/tab/tab.tsx
Labels: 🪛 fix, 🦁 정훈

#107 Feat: 분실물 메인 페이지
  src/pages/lost-items/constants/.gitkeep
  src/pages/lost-items/constants/lostItems.ts
  src/pages/lost-items/lost-items.css.ts
  src/pages/lost-items/lost-items.tsx
  src/shared/components/card/card.css.ts
  src/shared/components/card/card.tsx
Labels: 📣 feature, 🦦 윤하

#121 Fix: Input 컴포넌트 클릭 전 css 수정
  src/shared/components/input/input.css.ts
Labels: 🪛 fix, 🦦 윤하
